// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgFR4dbasRe2nAm-F0mHe2jJXFMEM5swo',
    appId: '1:1089255032869:web:a130333ae01ee506cc97cc',
    messagingSenderId: '1089255032869',
    projectId: 'fir-flutter-codelab-790fe',
    authDomain: 'fir-flutter-codelab-790fe.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-790fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Ap8aGzcy3no04MTsr9-C_0kjf0-vO30',
    appId: '1:1089255032869:android:71411c8e24dabd10cc97cc',
    messagingSenderId: '1089255032869',
    projectId: 'fir-flutter-codelab-790fe',
    storageBucket: 'fir-flutter-codelab-790fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCQpds1lzF9z9GMijPHSIgoTI57cjauqw',
    appId: '1:1089255032869:ios:3d06a481f2d970e7cc97cc',
    messagingSenderId: '1089255032869',
    projectId: 'fir-flutter-codelab-790fe',
    storageBucket: 'fir-flutter-codelab-790fe.appspot.com',
    iosClientId: '1089255032869-bhegiiuodt2h0od81s0a1iqe88qtkmgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCQpds1lzF9z9GMijPHSIgoTI57cjauqw',
    appId: '1:1089255032869:ios:cfd3bad83bd8ee8ecc97cc',
    messagingSenderId: '1089255032869',
    projectId: 'fir-flutter-codelab-790fe',
    storageBucket: 'fir-flutter-codelab-790fe.appspot.com',
    iosClientId: '1089255032869-ajektcogj120u976aleup62k6rhom6bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
